/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Atharva
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    JPanel workArea;
    PersonDirectory personDirectory;
    Person person;
    public ViewPersonJPanel(JPanel container, PersonDirectory directory, Person person) {
        initComponents();
        this.workArea = container;
        this.personDirectory = directory;
        this.person = person;
        refreshTextFields();
        setViewMode();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lbFirstName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lbSSN = new javax.swing.JLabel();
        lbAnnuaIncome = new javax.swing.JLabel();
        lbBodyWeight = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbStreetAddress = new javax.swing.JLabel();
        lbCity = new javax.swing.JLabel();
        lbUnitNumber = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        txtUnitNumber = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lbState = new javax.swing.JLabel();
        lbContactNumber = new javax.swing.JLabel();
        lbZipCode = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lbHomeAddress = new javax.swing.JLabel();
        txtBodyWeight = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lbStreetAddress1 = new javax.swing.JLabel();
        lbCity1 = new javax.swing.JLabel();
        lbUnitNumber1 = new javax.swing.JLabel();
        txtStreetAddress1 = new javax.swing.JTextField();
        txtUnitNumber1 = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        lbState1 = new javax.swing.JLabel();
        lbContactNumber1 = new javax.swing.JLabel();
        lbZipCode1 = new javax.swing.JLabel();
        txtState1 = new javax.swing.JTextField();
        txtZipCode1 = new javax.swing.JTextField();
        txtContactNumber1 = new javax.swing.JTextField();
        lbDOB = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbHomeAddress1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("VIEW PERSON");

        lbFirstName.setText("First Name :");

        lbSSN.setText("SSN:");

        lbAnnuaIncome.setText("Annual Income:");

        lbBodyWeight.setText("Body Weight :");

        jInternalFrame1.setVisible(true);

        lbStreetAddress.setText("Street Address:");

        lbCity.setText("City:");

        lbUnitNumber.setText("Unit Number:");

        lbState.setText("State:");

        lbContactNumber.setText("Contact Number:");

        lbZipCode.setText("Zip Code:");

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });

        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lbStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lbUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStreetAddress)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUnitNumber)
                    .addComponent(txtUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbZipCode)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContactNumber)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lbHomeAddress.setText("Home Address");

        lbLastName.setText("Last Name:");

        jInternalFrame2.setVisible(true);

        lbStreetAddress1.setText("Street Address:");

        lbCity1.setText("City:");

        lbUnitNumber1.setText("Unit Number:");

        lbState1.setText("State:");

        lbContactNumber1.setText("Contact Number:");

        lbZipCode1.setText("Zip Code:");

        txtZipCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCode1ActionPerformed(evt);
            }
        });

        txtContactNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumber1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lbStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbState1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lbCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lbUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStreetAddress1)
                    .addComponent(txtStreetAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbState1)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUnitNumber1)
                    .addComponent(txtUnitNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbZipCode1)
                    .addComponent(txtZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCity1)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContactNumber1)
                    .addComponent(txtContactNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDOB.setText("DOB:");

        lbAge.setText("Age:");

        lbHomeAddress1.setText("Office Address");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHomeAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(93, 93, 93)
                                .addComponent(btnSave)
                                .addGap(109, 109, 109)
                                .addComponent(btnUpdate))
                            .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbAge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbAnnuaIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lbFirstName)
                .addGap(279, 279, 279)
                .addComponent(lbHomeAddress1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLastName)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSSN)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDOB)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAnnuaIncome)
                        .addComponent(txtAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbBodyWeight)
                        .addComponent(txtBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addComponent(lbHomeAddress)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void txtZipCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCode1ActionPerformed

    private void txtContactNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumber1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int age;
        float bodyWeight;
        double annualIncome;
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String dob =txtDOB.getText();
        String ssn =txtSSN.getText();
        String homeStreetAddress =txtStreetAddress.getText();
        String homeUnitNumber = txtUnitNumber.getText();
        String homeZipCode = txtZipCode.getText();
        String homeState = txtState.getText();
        String homeContact = txtContactNumber.getText();
        String officeStreetAddress = txtStreetAddress1.getText();
        String officeUnitNuber = txtUnitNumber1.getText();
        String officeZipCode = txtZipCode1.getText();
        String officeState = txtState1.getText();
        String officeContact = txtContactNumber1.getText();
        String officeCity = txtCity1.getText();
        
        if (firstName.isBlank() || lastName.isBlank()|| dob.isBlank() || ssn.isBlank() || homeStreetAddress.isBlank() || homeUnitNumber.isBlank() || homeZipCode.isBlank() || homeState.isBlank() || homeContact.isBlank() ||
                officeStreetAddress.isBlank() || officeUnitNuber.isBlank() || officeCity.isBlank() || officeState.isBlank() || officeZipCode.isBlank() || officeContact.isBlank()){
            JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.WARNING_MESSAGE);
           return;
        }
    
        try{
            age = Integer.parseInt(txtAge.getText());
         }   catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check age","Warning", JOptionPane.WARNING_MESSAGE);
            return ;
        }
        try {
    bodyWeight = Float.parseFloat(txtBodyWeight.getText());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Please Check the Body Weight Input", "Warning", JOptionPane.WARNING_MESSAGE);
    return;
}
        try {
    annualIncome = Double.parseDouble(txtAnnualIncome.getText());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Please Check the Annual Income Input", "Warning", JOptionPane.WARNING_MESSAGE);
    return;
}
        Person p = personDirectory.addPerson();
person.setFirstName(firstName);
person.setLastName(lastName);
person.setAge(age);
person.setDateOfBirth(dob);
person.setSocialSecurityNumber(ssn);
person.setHomeAddress(homeStreetAddress, homeUnitNumber, homeZipCode, ssn, homeState, homeUnitNumber);
person.setOfficeAddress(homeStreetAddress, homeUnitNumber, homeZipCode, ssn, homeState, homeUnitNumber);
  JOptionPane.showMessageDialog(null, "Person Successfully Added", "Information", JOptionPane.INFORMATION_MESSAGE);
  
txtFirstName.setText("");
txtLastName.setText("");
txtAge.setText("");
txtDOB.setText("");
txtSSN.setText("");
txtStreetAddress.setText("");
txtUnitNumber.setText("");
txtZipCode.setText("");
txtCity.setText("");
txtState.setText("");
txtContactNumber.setText("");
txtStreetAddress1.setText("");
txtUnitNumber1.setText("");
txtZipCode1.setText("");
txtCity1.setText("");
txtState1.setText("");
txtContactNumber1.setText("");
txtAnnualIncome.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAnnuaIncome;
    private javax.swing.JLabel lbBodyWeight;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCity1;
    private javax.swing.JLabel lbContactNumber;
    private javax.swing.JLabel lbContactNumber1;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbHomeAddress;
    private javax.swing.JLabel lbHomeAddress1;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbSSN;
    private javax.swing.JLabel lbState;
    private javax.swing.JLabel lbState1;
    private javax.swing.JLabel lbStreetAddress;
    private javax.swing.JLabel lbStreetAddress1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUnitNumber;
    private javax.swing.JLabel lbUnitNumber1;
    private javax.swing.JLabel lbZipCode;
    private javax.swing.JLabel lbZipCode1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtBodyWeight;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtContactNumber1;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtStreetAddress1;
    private javax.swing.JTextField txtUnitNumber;
    private javax.swing.JTextField txtUnitNumber1;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtZipCode1;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
    txtFirstName.setText(person.getFirstName());
    txtLastName.setText(person.getLastName());
    txtDOB.setText(person.getDob());
    txtSSN.setText(person.getSocialSecurityNumber());
    txtStreetAddress.setText(person.getHomeStreet());
    txtUnitNumber.setText(person.getHomeUnit());
    txtZipCode.setText(person.getHomeZip());
    txtCity.setText(person.getHomeCity());
    txtState.setText(person.getHomeState());
    txtContactNumber.setText(person.getHomeNumber());
    txtStreetAddress1.setText(person.getOfficeStreet());
    txtUnitNumber1.setText(person.getOfficeUnit());
    txtZipCode1.setText(person.getOfficeZip());
    txtCity1.setText(person.getOfficeCity());
    txtState1.setText(person.getOfficeState());
    txtContactNumber1.setText(person.getOfficeNumber());
    txtAge.setText(String.valueOf( person.getAge())); // for int
    txtAnnualIncome.setText(String.valueOf(person.getAnnualIncome())); // for double or float
    txtBodyWeight.setText(String.valueOf(person.getBodyWeight()));    }

    private void setViewMode() {
    txtFirstName.setEnabled(false);
    txtLastName.setEnabled(false);
    txtDOB.setEnabled(false);
    txtSSN.setEnabled(false);
    txtStreetAddress.setEnabled(false);
    txtUnitNumber.setEnabled(false);
    txtZipCode.setEnabled(false);
    txtCity.setEnabled(false);
    txtState.setEnabled(false);
    txtContactNumber.setEnabled(false);
    txtStreetAddress1.setEnabled(false);
    txtUnitNumber1.setEnabled(false);
    txtZipCode1.setEnabled(false);
    txtCity1.setEnabled(false);
    txtState1.setEnabled(false);
    txtContactNumber1.setEnabled(false);
    txtAge.setEnabled(false);
    txtAnnualIncome.setEnabled(false);
    txtBodyWeight.setEnabled(false);
    
    // Disable buttons
    btnSave.setEnabled(false);
    btnUpdate.setEnabled(true);
    }

    private void setEditMode() {
        txtFirstName.setEnabled(true);
    txtLastName.setEnabled(true);
    txtDOB.setEnabled(true);
    txtSSN.setEnabled(true);
    txtStreetAddress.setEnabled(true);
    txtUnitNumber.setEnabled(true);
    txtZipCode.setEnabled(true);
    txtCity.setEnabled(true);
    txtState.setEnabled(true);
    txtContactNumber.setEnabled(true);
    txtStreetAddress1.setEnabled(true);
    txtUnitNumber1.setEnabled(true);
    txtZipCode1.setEnabled(true);
    txtCity1.setEnabled(true);
    txtState1.setEnabled(true);
    txtContactNumber1.setEnabled(true);
    txtAge.setEnabled(true);
    txtAnnualIncome.setEnabled(true);
    txtBodyWeight.setEnabled(true);
    
    // Enable buttons
    btnSave.setEnabled(true);
    btnUpdate.setEnabled(false);
    }
}
