/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JFrame;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkAreaJPanel;

/**
 *
 * @author Atharva
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private PersonDirectory personDirectory;
    public MainJFrame() {
        initComponents();
        this.personDirectory = new PersonDirectory ();
        generateDemoData();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        titlePanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        btnGoToWorkArea = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lbTitle.setBackground(new java.awt.Color(51, 255, 255));
        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(153, 204, 255));
        lbTitle.setText("PERSON PROFILE");

        btnGoToWorkArea.setBackground(new java.awt.Color(153, 255, 255));
        btnGoToWorkArea.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnGoToWorkArea.setText("Click here to view and manage person profiles.");
        btnGoToWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToWorkAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnGoToWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoToWorkArea))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSplitPane.setTopComponent(titlePanel);

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToWorkAreaActionPerformed
        // TODO add your handling code here:
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(workArea, personDirectory);
        workArea.add("PersonMngWorkArea", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
        
    }//GEN-LAST:event_btnGoToWorkAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToWorkArea;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        Person newPersonOne = personDirectory.addPerson();
        newPersonOne.setFirstName("Atharva");
        newPersonOne.setLastName("Gadgil");
        newPersonOne.setDateOfBirth("13/07/2002");
        newPersonOne.setAge(22);
        newPersonOne.setBodyWeight(70.22f);
        newPersonOne.setAnnualIncome(890000.00);
        newPersonOne.setSocialSecurityNumber("1236547890");
        newPersonOne.setHomeAddress("13 Ruggles", "Unit 1", "02119", "Boston", "MA", "9833610286");
        newPersonOne.setOfficeAddress("13 Shawmut Ave", "2", "02119", "Boston", "MA", "8573985100");
        // add another
        Person newPersonTwo = personDirectory.addPerson();
        newPersonTwo.setFirstName("John");
        newPersonTwo.setLastName("Doe");
        newPersonTwo.setDateOfBirth("11/12/2000");
        newPersonTwo.setAge(23);
        newPersonTwo.setBodyWeight(70.77f);
        newPersonTwo.setAnnualIncome(890000.00);
        newPersonTwo.setSocialSecurityNumber("1111111111");
        newPersonTwo.setHomeAddress("13 Ruggles", "508", "400014", "Mumbai", "MH", "7021945060");
        newPersonTwo.setOfficeAddress("13 Dhuvela", "13", "400014", "Mumbai", "MH", "8756984789");
        
        Person newPersonThree = personDirectory.addPerson();
        newPersonThree.setFirstName("Nicolas");
        newPersonThree.setLastName("Jackson");
        newPersonThree.setDateOfBirth("05/03/2001");
        newPersonThree.setBodyWeight(89.99f);
        newPersonThree.setAnnualIncome(750000.00);
        newPersonThree.setAge(25);
        newPersonThree.setSocialSecurityNumber("3333333333");
        newPersonThree.setHomeAddress("9 Ruggles", "Unit 3", "02119", "Boston", "MA", "8373388032");
        newPersonThree.setOfficeAddress("13 Moreland Ave", "4", "02119", "Boston", "MA", "8372888899");
        
        Person newPersonFour = personDirectory.addPerson();
        newPersonFour.setFirstName("Bukayo");
        newPersonFour.setLastName("Saka");
        newPersonFour.setDateOfBirth("04/03/1990");
        newPersonFour.setBodyWeight(49.99f);
        newPersonFour.setAnnualIncome(740000.00);
        newPersonFour.setAge(22);
        newPersonFour.setSocialSecurityNumber("2222222222");
        newPersonFour.setHomeAddress("327 Huntington Ave", "Unit 4", "02115", "Boston", "MA", "8376688094");
        newPersonFour.setOfficeAddress("16 Symphony Ave", "2", "02119", "Boston", "MA", "6172888899");
        
        Person newPersonFive = personDirectory.addPerson();
        newPersonFive.setFirstName("Melvin");
        newPersonFive.setLastName("Pareira");
        newPersonFive.setDateOfBirth("13/09/2001");
        newPersonFive.setBodyWeight(59.99f);
        newPersonFive.setAnnualIncome(730000.00);
        newPersonFive.setAge(23);
        newPersonFive.setSocialSecurityNumber("4444444444");
        newPersonFive.setHomeAddress("Kranti Nagar", "2", "400034", "Mumbai", "MH", "9887653679");
        newPersonFive.setOfficeAddress("17 Hiranandani Estate", "12", "400019", "Thane", "MH", "9876543213");

        
    }
}
