/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Profile;

/**
 *
 * @author Atharva
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    Profile profile;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Profile p) {
        profile = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        lbFirstname = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbLastname = new javax.swing.JLabel();
        txtLastame1 = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lbphone = new javax.swing.JLabel();
        txtDriverLicenseNumber = new javax.swing.JTextField();
        lbDriverLicenseNumber = new javax.swing.JLabel();
        txtDriverLicenseState = new javax.swing.JTextField();
        lbDriverLinceseState = new javax.swing.JLabel();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        lbSocialSecurityNumber = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        lbAddressLine1 = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        lbAddressLine2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lbCity = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lbState = new javax.swing.JLabel();
        txtZIP = new javax.swing.JTextField();
        lbZIP = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        lbTelephone = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        lbFaxNumber = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lbGender = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lbDOB = new javax.swing.JLabel();
        txtOriginCountry = new javax.swing.JTextField();
        lbOriginCountry = new javax.swing.JLabel();
        txtEthnicity = new javax.swing.JTextField();
        lbEthnicity = new javax.swing.JLabel();
        txtPassportNumber = new javax.swing.JTextField();
        lbPassportNumber = new javax.swing.JLabel();
        txtLanguagePreference = new javax.swing.JTextField();
        lbLanguagePreference = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lbCreateProfile = new javax.swing.JLabel();

        lbFirstname.setText("FirstName");

        lbLastname.setText("LastName");

        lbEmail.setText("Email");

        lbphone.setText("Phone");

        lbDriverLicenseNumber.setText("DriverLicenseNumber");

        lbDriverLinceseState.setText("DriverLicenseState");

        lbSocialSecurityNumber.setText("SocialSecurityNumber");

        lbAddressLine1.setText("AddressLine1");

        lbAddressLine2.setText("AddressLine2");

        lbCity.setText("City");

        lbState.setText("State");

        lbZIP.setText("ZIP");

        lbTelephone.setText("Telephone ");

        lbFaxNumber.setText("FaxNumber");

        lbGender.setText("Gender");

        lbDOB.setText("DOB");

        lbOriginCountry.setText("OriginCountry");

        lbEthnicity.setText("Ethnicity");

        lbPassportNumber.setText("PassportNumber");

        lbLanguagePreference.setText("LanguagePreference");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbCreateProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCreateProfile.setText("Create Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDriverLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDriverLinceseState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSocialSecurityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbZIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFaxNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbOriginCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEthnicity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPassportNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLanguagePreference, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLanguagePreference)
                    .addComponent(txtPassportNumber)
                    .addComponent(txtEthnicity)
                    .addComponent(txtOriginCountry)
                    .addComponent(txtDOB)
                    .addComponent(txtGender)
                    .addComponent(txtFaxNumber)
                    .addComponent(txtTelephone)
                    .addComponent(txtZIP)
                    .addComponent(txtState)
                    .addComponent(txtCity)
                    .addComponent(txtAddressLine2)
                    .addComponent(txtAddressLine1)
                    .addComponent(txtSocialSecurityNumber)
                    .addComponent(txtDriverLicenseState)
                    .addComponent(txtDriverLicenseNumber)
                    .addComponent(txtPhone)
                    .addComponent(txtEmail)
                    .addComponent(txtFirstName)
                    .addComponent(txtLastame1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(70, 70, 70))
            .addComponent(lbCreateProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbCreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstName)
                    .addComponent(lbFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLastname)
                    .addComponent(txtLastame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDriverLicenseNumber))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDriverLicenseState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbDriverLinceseState, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddressLine1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddressLine2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbZIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFaxNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOriginCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbOriginCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEthnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEthnicity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassportNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLanguagePreference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLanguagePreference))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstname = txtFirstName.getText();
        String lastname = txtLastame1.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String driverlicensenumber = txtDriverLicenseNumber.getText();
        String driverlicensestate = txtDriverLicenseState.getText();
        String socialsecuritynumber = txtSocialSecurityNumber.getText();
        String addressline1 = txtAddressLine1.getText();
        String addressline2 = txtAddressLine2.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        String zip = txtZIP.getText();
        String telephone = txtTelephone.getText();
        String faxnumber = txtFaxNumber.getText();
        String gender = txtGender.getText();
        String dob = txtDOB.getText();
        String origincountry = txtOriginCountry.getText();
        String ethnicity = txtEthnicity.getText();
        String passportnumber = txtPassportNumber.getText();
        String languagepreference = txtLanguagePreference.getText();
        
        profile.setFirstName(firstname);
        profile.setLastName(lastname);
        profile.setEmail(email);
        profile.setPhone(phone);
        profile.setDriversLicenseNumber(driverlicensenumber);
        profile.setDriversLicenseState(driverlicensestate);
        profile.setSocialSecurityNumber(socialsecuritynumber);
        profile.setAddressLine1(addressline1);
        profile.setAddressLine2(addressline2);
        profile.setCity(city);
        profile.setState(state);
        profile.setZIP(zip);
        profile.setTelephone(telephone);
        profile.setFaxNumber(faxnumber);
        profile.setGender(gender);
        profile.setDOB(dob);
        profile.setOriginCountry(origincountry);
        profile.setEthnicity(ethnicity);
        profile.setPassportNumber(passportnumber);
        profile.setLanguage(lastname);
        
        JOptionPane.showMessageDialog(this,"Profile Saved!","SUCCESS!",JOptionPane.PLAIN_MESSAGE);
        
        txtFirstName.setText("");
        txtLastame1.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtDriverLicenseNumber.setText("");
        txtDriverLicenseState.setText("");
        txtSocialSecurityNumber.setText("");
        txtAddressLine1.setText("");
        txtAddressLine2.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZIP.setText("");
        txtTelephone.setText("");
        txtFaxNumber.setText("");
        txtGender.setText("");
        txtDOB.setText("");
        txtOriginCountry.setText("");
        txtEthnicity.setText("");
        txtPassportNumber.setText("");
        txtLanguagePreference.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbAddressLine1;
    private javax.swing.JLabel lbAddressLine2;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCreateProfile;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbDriverLicenseNumber;
    private javax.swing.JLabel lbDriverLinceseState;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEthnicity;
    private javax.swing.JLabel lbFaxNumber;
    private javax.swing.JLabel lbFirstname;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbLanguagePreference;
    private javax.swing.JLabel lbLastname;
    private javax.swing.JLabel lbOriginCountry;
    private javax.swing.JLabel lbPassportNumber;
    private javax.swing.JLabel lbSocialSecurityNumber;
    private javax.swing.JLabel lbState;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JLabel lbZIP;
    private javax.swing.JLabel lbphone;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDriverLicenseNumber;
    private javax.swing.JTextField txtDriverLicenseState;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEthnicity;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLanguagePreference;
    private javax.swing.JTextField txtLastame1;
    private javax.swing.JTextField txtOriginCountry;
    private javax.swing.JTextField txtPassportNumber;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtZIP;
    // End of variables declaration//GEN-END:variables
}
